#pragma once

#define SPT_NOTIFICATION_VERSION_MAJOR 2
#define SPT_NOTIFICATION_VERSION_MINOR 24
#define SPT_NOTIFICATION_VERSION_PATCH 4

#ifndef MAKE_SEMANTIC_VERSION
#define MAKE_SEMANTIC_VERSION(major, minor, patch) ((major << 24) | (minor << 16) | patch)
#endif

#define SPT_NOTIFICATION_VERSION_INT \
	MAKE_SEMANTIC_VERSION(SPT_NOTIFICATION_VERSION_MAJOR, SPT_NOTIFICATION_VERSION_MINOR, SPT_NOTIFICATION_VERSION_PATCH)

#define SPT_NOTIFICATION_MACRO_STR_(x) #x
#define SPT_NOTIFICATION_MACRO_STR(x) SPT_NOTIFICATION_MACRO_STR_(x)

#define SPT_NOTIFICATION_VERSION_STRING                       \
	SPT_NOTIFICATION_MACRO_STR(SPT_NOTIFICATION_VERSION_MAJOR) \
	"." SPT_NOTIFICATION_MACRO_STR(SPT_NOTIFICATION_VERSION_MINOR) "." SPT_NOTIFICATION_MACRO_STR(SPT_NOTIFICATION_VERSION_PATCH)
