#pragma once

#define OBS_NOTIFICATION_VERSION_MAJOR 2
#define OBS_NOTIFICATION_VERSION_MINOR 24
#define OBS_NOTIFICATION_VERSION_PATCH 4

#ifndef MAKE_SEMANTIC_VERSION
#define MAKE_SEMANTIC_VERSION(major, minor, patch) ((major << 24) | (minor << 16) | patch)
#endif

#define OBS_NOTIFICATION_VERSION_INT \
	MAKE_SEMANTIC_VERSION(OBS_NOTIFICATION_VERSION_MAJOR, OBS_NOTIFICATION_VERSION_MINOR, OBS_NOTIFICATION_VERSION_PATCH)

#define OBS_NOTIFICATION_MACRO_STR_(x) #x
#define OBS_NOTIFICATION_MACRO_STR(x) OBS_NOTIFICATION_MACRO_STR_(x)

#define OBS_NOTIFICATION_VERSION_STRING                       \
	OBS_NOTIFICATION_MACRO_STR(OBS_NOTIFICATION_VERSION_MAJOR) \
	"." OBS_NOTIFICATION_MACRO_STR(OBS_NOTIFICATION_VERSION_MINOR) "." OBS_NOTIFICATION_MACRO_STR(OBS_NOTIFICATION_VERSION_PATCH)
